-- Database: dishes

-- DROP DATABASE IF EXISTS dishes;

CREATE DATABASE dishes
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Ukrainian_Ukraine.1251'
    LC_CTYPE = 'Ukrainian_Ukraine.1251'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;


-- Table: dishes.dishes

-- DROP TABLE IF EXISTS dishes.dishes;

CREATE TABLE IF NOT EXISTS dishes.dishes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    price numeric NOT NULL,
    CONSTRAINT dishes_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS dishes.dishes
    OWNER to postgres;

-- Table: orders.orders

-- DROP TABLE IF EXISTS orders.orders;

CREATE TABLE IF NOT EXISTS orders.orders
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    table_id integer NOT NULL,
    dishes integer[] NOT NULL,
    order_sum numeric NOT NULL,
    sum_no_vat numeric NOT NULL,
    tip numeric NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS dishes.orders
    OWNER to postgres;

-- Insert demo data

INSERT INTO dishes.dishes(
	name, price)
	VALUES ('salad', '12.2');

INSERT INTO orders.orders(
	table_id, dishes, order_sum, sum_no_vat, tip)
	VALUES (1, [1, 2, 3], 23.2, 132.1, 11.0);
