name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Clean
      working-directory: ./docs/lab2
      run: make clean

    - name: Vet
      working-directory: ./docs/lab2
      run: make vet

    - name: Test
      working-directory: ./docs/lab2
      run: make test
